# Generated by Django 6.0.7 on 2026-08-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Confirmée', 'Confirmée'), ('Livrée', 'Livrée')], default='En attente', max_length=20),
        ),
    ]
