# Generated by Django 6.0.7 on 2026-08-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orderitem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, help_text='Séparer les tailles par des virgules. Exemple: S,M,L,XL ou 40,41,42', max_length=200),
        ),
    ]
